package com.dbinsightai.dbinsight_ai.ai.service.impl;

import com.dbinsightai.dbinsight_ai.ai.dto.GeminiRequest;
import com.dbinsightai.dbinsight_ai.ai.dto.GeminiResponse;
import com.dbinsightai.dbinsight_ai.ai.service.GeminiService;
import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestClient;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
@Service
@RequiredArgsConstructor
public class GeminiServiceImpl implements GeminiService {

    private final RestClient restClient;
    private final ObjectMapper objectMapper = new ObjectMapper();

    @Value("${gemini.api.key}")
    private String apiKey;

    @Value("${gemini.api.url}")
    private String apiUrl;

    @Override
    public GeminiResponse optimize(GeminiRequest request) {

        String prompt = """
You are DBInsight AI.

Analyze this PostgreSQL query.

Return ONLY valid JSON.

{
  "optimizedQuery":"",
  "explanation":"",
  "performanceScore":0,
  "indexSuggestions":[]
}

Keep the explanation under 80 words.

SQL:
""" + request.getSqlQuery();

        String requestBody = """
                {
                  "contents": [
                    {
                      "parts": [
                        {
                          "text": "%s"
                        }
                      ]
                    }
                  ]
                }
                """.formatted(prompt.replace("\"", "\\\""));

        String response = restClient.post()
                .uri(apiUrl + "?key=" + apiKey)
                .header("Content-Type", "application/json")
                .body(requestBody)
                .retrieve()
                .body(String.class);

        try {

            JsonNode root = objectMapper.readTree(response);

            String text = root
                    .path("candidates")
                    .get(0)
                    .path("content")
                    .path("parts")
                    .get(0)
                    .path("text")
                    .asText();

            return GeminiResponse.builder()
                    .optimizedQuery(text)
                    .explanation("Generated by Gemini")
                    .build();

        } catch (Exception e) {

            throw new RuntimeException("Failed to parse Gemini response", e);

        }
    }
}